// <auto-generated />
using System;
using InfoSystem.Infrastructure.DataBase.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace InfoSystem.Infrastructure.Migrations
{
    [DbContext(typeof(InfoSystemDbContext))]
    [Migration("20190106195231_basic-EAV-Implementation")]
    partial class basicEAVImplementation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("InfoSystem.Core.Entities.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Editable");

                    b.Property<int>("EntityId");

                    b.HasKey("Id");

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("InfoSystem.Core.Entities.EntityProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EntityId");

                    b.Property<int>("PropertyId");

                    b.HasKey("Id");

                    b.ToTable("EntityProperties");
                });

            modelBuilder.Entity("InfoSystem.Core.Entities.Market", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Markets");
                });

            modelBuilder.Entity("InfoSystem.Core.Entities.MarketProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("MarketId1");

                    b.Property<int?>("ProductId1");

                    b.HasKey("Id");

                    b.HasIndex("MarketId1");

                    b.HasIndex("ProductId1");

                    b.ToTable("MarketProducts");
                });

            modelBuilder.Entity("InfoSystem.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("InfoSystem.Core.Entities.Properties", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("EntityId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("InfoSystem.Core.Entities.PropertyValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("PropertyId");

                    b.Property<int>("ValueId");

                    b.HasKey("Id");

                    b.ToTable("PropertyValues");
                });

            modelBuilder.Entity("InfoSystem.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InfoSystem.Core.Entities.Values", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("Values");
                });

            modelBuilder.Entity("InfoSystem.Core.Entities.MarketProduct", b =>
                {
                    b.HasOne("InfoSystem.Core.Entities.Market")
                        .WithMany("Products")
                        .HasForeignKey("MarketId1");

                    b.HasOne("InfoSystem.Core.Entities.Product")
                        .WithMany("InMarkets")
                        .HasForeignKey("ProductId1");
                });

            modelBuilder.Entity("InfoSystem.Core.Entities.Properties", b =>
                {
                    b.HasOne("InfoSystem.Core.Entities.Entity")
                        .WithMany("Properties")
                        .HasForeignKey("EntityId");
                });
#pragma warning restore 612, 618
        }
    }
}
